    pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'chmod +x ./gradlew'
                sh './gradlew build'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am Sonarqube Scan"
                ''',
            label: "static code analysis"
            }
        }
        stage('Build DockerImage')
        {
             steps {
            sh script: '''
                docker build -t "MerchantGalaxy" -f Dockerfile .
                '''
            }
        }
        stage('Publish DockerImage')	      
        {	        
                    steps {
                      sh script: '''
                                        echo "I am Pubishing DockerImage ="
                           ''',
            	            label: "Publishing Docker Image"
                    } 
          }
    }
        
    }
    
