pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'chmod +x ./gradlew'
                sh './gradlew build'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am Sonarqube Scan"
                ''',
            label: "static code analysis"
            }
        }
        stage('Build DockerImage')
        {
             steps {
            sh script: '''
                docker build -t "merchantgalaxy" -f .infra/docker/Dockerfile .
                '''
            }
        }
        stage('Publish DockerImage')	      
        {	        
                     steps {
                sh "docker login -u tapsi -p tapsi@123"
                sh "docker tag merchantgalaxy:latest tapsi/merchantgalaxy:latest"
                sh "docker push tapsi/merchantgalaxy:latest"
            }
        }
    }
    post{
        always{
            deleteDir()
    }
    }
}